project:
  type: website
  render:
    - pg_index.qmd
    - pg_services.qmd
    - pg_who_is_slc.qmd
    - pg_contact.qmd

website:
  favicon: images/favicon_logo.png
  navbar:
    left:
      - href: pg_index.qmd
        text: Home
      - pg_services.qmd
      - href: pg_who_is_slc.qmd
        text: About
      - pg_contact.qmd
    tools: 
      - icon: envelope-at
        href: angie@summitlineconsulting.com
      - icon: linkedin
        href: www.linkedin.com/in/angie-naillon
    
format:
  html:
    theme: styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true
    page-layout: full
    
execute: 
  freeze: auto
  
  
  
