project:
  type: website
  render:
    - index.qmd

website:
  title: "SLC"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: minty
    # css: styles.css
    toc: true
    
execute: 
  freeze: auto