project:
  type: website
  render:
    - index.qmd
    - services.qmd
    - who_is_slc.qmd
    - contact.qmd

website:
  favicon: images/Favicon_logo.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: who_is_slc.qmd
        text: About
      - contact.qmd
    tools: 
      - icon: envelope-at
        href: mailto:angie@summitlineconsulting.com
      - icon: linkedin
        href: https://www.linkedin.com/in/angie-naillon
    
format:
  html:
    theme: styles.scss
    # css: styles.css
    mainfont: Nunito
    toc: true
    page-layout: full
    
execute: 
  freeze: auto
  
  
  
